apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: backstage
  description: Backstage application.
  # Example for optional annotations
  # annotations:
  #   github.com/project-slug: backstage/backstage
  #   backstage.io/techdocs-ref: dir:.
spec:
  type: website
  owner: john@example.com
  lifecycle: experimental

  import:
      entityFilename: catalog-info.yaml
      pullRequestBranchName: backstage-integration
  
  rules:
    - allow: [Component, System, API, Resource, Location]
  locations:
    - type: file
      target: backstage/examples/entities.yaml

    - type: file
      target: backstage/examples/template/template.yaml
      rules:
        - allow: [Template]

    - type: file
      target: backstage/examples/org.yaml
      rules:
        - allow: [User, Group]

